ProyectoMentopoker/Controllers/EstadisticasController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoMentopoker.Filters;
using ProyectoMentopoker.Models;
using ProyectoMentopoker.Repositories;
namespace ProyectoMentopoker.Controllers
{
    public class EstadisticasController : Controller
    {
        private RepositoryTablas repoTablas;
        private RepositoryEstadisticas repoStats;

        public EstadisticasController(RepositoryEstadisticas repoStats)
        {
            this.repoTablas = new RepositoryTablas();
            this.repoStats = repoStats;
        }


        [AuthorizeUsers]
        public IActionResult VerPartidas()
        {
            //var usuario_id = HttpContext.Session.GetString("ID");

            //if (usuario_id == null)
            //{
            //    usuario_id = "1";
            //}
            //ConjuntoPartidasUsuario conjunto = this.repoStats.GetPartidas(int.Parse(usuario_id), "partidas");

            return View();
        }


        [HttpPost]
        public IActionResult VerPartidas(DateTime? fechaInicio = null, DateTime? fechaFinal = null)
        {

            //var usuario_id = HttpContext.Session.GetString("ID");
            var usuario_id = User.FindFirst("ID")?.Value;
            if (usuario_id == null)
            {
                usuario_id = "1";
            }
            EstadisticasPartidas stats = this.repoStats.GetEstadisticasPartidas(int.Parse(usuario_id), "partidas", fechaInicio, fechaFinal);

            return View(stats);

        }


        [AuthorizeUsers]
        public IActionResult VerJugadas()
        {
            //var usuario_id = HttpContext.Session.GetString("ID");

            //if (usuario_id == null)
            //{
            //    usuario_id = "1";
            //}
            //ConjuntoPartidasUsuario conjunto = this.repoStats.GetPartidas(int.Parse(usuario_id), "jugadas");

            return View();
        }


        [HttpPost]
        public IActionResult VerJugadas(DateTime? fechaInicio = null, DateTime? fechaFinal = null, string? cell_id = null, int? condicion = null, double? cantidadJugada = null)
        {


            string peticion = "";
            var usuario_id = User.FindFirst("ID")?.Value;
           

            if (usuario_id == null)
            {
                usuario_id = "1";
            }

            if (fechaInicio != null || fechaFinal !=null)
            {
                peticion = "jugadasFecha";
            }
            if(cell_id != null)
            {
                peticion = "jugadasCellid";
            }

            if(condicion != null)
            {

                peticion = "jugadasCondicion";
            }

            EstadisticasJugadas stats = this.repoStats.GetEstadisticasJugadas(int.Parse(usuario_id), peticion, fechaInicio, fechaFinal, cell_id, condicion, cantidadJugada);

            return View(stats);

        }


       



    }
}

ProyectoMentopoker/Controllers/PartidaConTablaController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoMentopoker.Filters;
using ProyectoMentopoker.Models;
using ProyectoMentopoker.Repositories;

namespace ProyectoMentopoker.Controllers
{
    public class PartidaConTablaController : Controller
    {

        private RepositoryTablas repoTablas;

        public PartidaConTablaController()
        {
            this.repoTablas = new RepositoryTablas();

        }


        [AuthorizeUsers]
        public IActionResult Jugar()
        {

            return View();
        }

        [HttpPost]
        public List<Celda> Jugar(int id)
        {

            List<Celda> tabla = this.repoTablas.GetTabla(id);
            return tabla;
        }

      



        public IActionResult insertar()
        {

            return View();
        }

        


        [HttpPost]
        public IActionResult insertar(int[] ids_Jugadas, int[] ids_Rondas, double[] ganancias_Rondas, double[] cantidades_Rondas,
            string[] cell_ids_Jugadas, int[] table_ids_Jugadas, double[] cantidades_Jugadas,
            Boolean[] seguimiento_jugadas, double dineroInicial, double dineroActual, string comentario, string usuario_id)
        {

            // Create a JSON object to return as the response
            var result = new
            {
                success = true,
                message = "Partida insertada correctamente"
            };

            this.repoTablas.insertPartida(ids_Jugadas, ids_Rondas, ganancias_Rondas, cantidades_Rondas, cell_ids_Jugadas, table_ids_Jugadas, cantidades_Jugadas, seguimiento_jugadas, dineroInicial, dineroActual, comentario, usuario_id);

            return Json(result);
        }
    }
}

ProyectoMentopoker/Controllers/PartidasController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoMentopoker.Models;
using ProyectoMentopoker.Repositories;

namespace ProyectoMentopoker.Controllers
{
    public class PartidasController : Controller
    {

        private RepositoryEstadisticas repo { get; set; }

        public PartidasController(RepositoryEstadisticas repo) {

            this.repo = repo;
        }

        public IActionResult Crud()
        {
            List<PartidaModel> partidas =  this.repo.GetAllPartidas();

            return View(partidas);
        }

        public IActionResult Update(string Partida_id)
        {
            PartidaModel partida = this.repo.FindPartida(Partida_id);
            return View(partida);

        }


        [HttpPost]
        public async Task<IActionResult> Update(PartidaModel partida)
        {
            await this.repo.UpdatePartida(partida.Partida_id, partida.Cash_Inicial, partida.Cash_Final, partida.Comentarios);

            return RedirectToAction("Crud");

        }


        public async Task<IActionResult> Delete(string Partida_id)
        {
            await this.repo.DeletePartida(Partida_id);
            return RedirectToAction("Crud");

        }


    }
}

ProyectoMentopoker/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoMentopoker.Repositories;
using ProyectoMentopoker.Models;
using ProyectoMentopoker.Filters;

namespace ProyectoMentopoker.Controllers
{
    public class UsuariosController : Controller
    {
        private RepositoryEstadisticas repoPartidas;
        private RepositoryLogin repoLogin;

        public UsuariosController(RepositoryLogin repoLogin, RepositoryEstadisticas repoPartidas)
        {
            this.repoLogin = repoLogin;
            this.repoPartidas = repoPartidas;

        }




        [AuthorizeUsers]
        public IActionResult Crud()
        {
            List<UsuarioModel> usuarios = this.repoLogin.GetUsuarios();
            return View(usuarios);
        }



        public IActionResult Insert()
        {     
            return View();

        }



        [HttpPost]
        public async Task<IActionResult> Insert(string Email, string Pass, string Nombre, string Rol)
        {
            await this.repoLogin.RegisterUsuario(Email, Pass, Nombre , Rol);

            //return RedirectToAction("Crud");
            return View();
        }

       

        public IActionResult Update(string Usuario_id)
        {
            UsuarioModel usuario = this.repoLogin.FindUsuario(Usuario_id);
            return View(usuario);

        }


        [HttpPost]
        public async Task<IActionResult> Update(string Usuario_id, string Email, string Nombre, string Rol)
        {
            await this.repoLogin.UpdateUsuario(Usuario_id, Email, Nombre, Rol);

            return RedirectToAction("Crud");

        }


        public async Task<IActionResult> Delete(string Usuario_id)
        {
            await this.repoPartidas.BorrarPartidas(Usuario_id);
             this.repoLogin.DeleteUsuario(Usuario_id);
            return RedirectToAction("Crud");

        }


    }
}

ProyectoMentopoker/Views/Shared/_Layout.cshtml
@using System.Security.Claims;

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Fixed top navbar example · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/navbar-fixed/">

    

    <!-- Bootstrap core CSS -->
         <link href="~/css/bootstrap.min.css" rel="stylesheet">
         <link href="~/css/NavBar.css" rel="stylesheet">
        




    
    <!-- Custom styles for this template -->
    @*<link href="~/css/navbar-top-fixed.css" rel="stylesheet">*@

  </head>
  <body>


    <style>
       html, body {
            height: 150%;
        }

        .body-background {
            background-image: linear-gradient(to bottom, #71C549, #1A2914);
            background-size: cover;
            height: 100%;
            padding: 100px 5% 600px 5%;
        }
        body .body-background .bg-light.colorfondo {
            background-color: transparent !important;
        }
 
       

     </style>
  
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark nav-background">
  <div class="container-fluid div-background">
            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" style="height:20%; width:20%;" /></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">

                <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
          <ul class="navbar-nav flex-grow-1">
                      
                       
             
                             <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="PartidaConTabla" asp-action="Jugar">Partida</a>
                        </li>
                         </li>
                             <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Estadisticas" asp-action="VerPartidas">Estadísticas partidas</a>
                        </li>
                            
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Estadisticas" asp-action="VerJugadas">Estadísticas jugadas</a>
                    </li>






                    </ul>

                  </div>




                @if
         (@Context.User.FindFirst(ClaimTypes.Role)?.Value == "admin")
                {
                    <div class="mx-auto order-0 justify-content-center">
                        <ul class="navbar-nav flex-grow-1">

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Usuarios" asp-action="Crud">Usuarios</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Partidas" asp-action="Crud">Partidas</a>
                            </li>
                        </ul>

                    </div>


               }

                
                    
            


                <div class="navbar-collapse collapse w-100 order-3 dual-collapse2 justify-content-end">

                        <ul class="navbar-nav me-auto">
                        <partial name="_MenuUsuario" />

                        </ul>
                </div>
               
     

           </div>

     @* <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>*@
    </div>
  </div>
</nav>


<main class="body-background">
  <div class="bg-light p-3 colorfondo">
    @RenderBody()
@*    <p>Pie de página</p>*@
  </div>
</main>




 
    <script src="~/js/jquery-3.6.3.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
      
    @RenderSection("scripts", false)
  </body>

</html>


  

ProyectoMentopoker/Views/Shared/_MenuUsuario.cshtml
@if (Context.User.Identity.IsAuthenticated == false){ 

                    
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                    </li>

}else{ 

                    <li>
                        <p></p>
                    </li>

                     <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="LogOut">LogOut
                         @*    <span style="color:white">@Context.User.FindFirst("NOMBRE")?.Value</span>*@
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Perfil" asp-action="PerfilUsuarios">Perfil</a>
                    </li>


}